apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: buildkit
  annotations:
    workflows.argoproj.io/description: |
      Build and push an image using Docker Buildkit. This does not need privileged access, unlike Docker in Docker (DIND).
    workflows.argoproj.io/maintainer: "@alexec"
    workflows.argoproj.io/tags: buildkit
    workflows.argoproj.io/version: ">= 2.9.0"
spec:
  templates:
    - name: image
      inputs:
        parameters:
          # Name of volume to mount
          - name: work
          # Path on the value
          - name: path
          # Name of the image to push
          - name: image
      # Mount the configuration so we can push the image.
      # This should create the /.docker/config.json file.
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
      container:
        image: moby/buildkit:v0.7.2-rootless
        volumeMounts:
          - name: "{{inputs.parameters.work}}"
            mountPath: /work
          - name: docker-config
            mountPath: /.docker
        workingDir: /work/{{inputs.parameters.path}}
        env:
          - name: BUILDKITD_FLAGS
            value: --oci-worker-no-process-sandbox
          - name: DOCKER_CONFIG
            value: /.docker
        command:
          - buildctl-daemonless.sh
        args:
          - build
          - --frontend
          - dockerfile.v0
          - --local
          - context=.
          - --local
          - dockerfile=.
          - --output
          - type=image,name=docker.io/{{inputs.parameters.image}},push=true
